### ISSUE TITLE
[ESP32-C3] Led turning on in fixed green.

### ISSUE THREAD

**Issue by jfdona23** [zorxx/neopixel#3]
Hi there! Thanks for the effort on doing this library!

I've an issue where the first LED turns on in green no matter what. Hardware in question is a dev board with an ESP32-C3 on it. 

My worskpace:

- ESP32-C3 dual USB-C board with onboard WS2812B LED.
- ESP-IDF v5.2.1-dirty (as VSCode extension)

Things I've tried so far:

- I used both LEDs: the onboard neopixel and a 8x8 matrix.
- Set LED to any other color than green. For example, red (rgb in decimal: 1048576).
- The fix stated in #2, but the library refused to compile.
- Your "test1" example.

The code so far (a bit trimmed):
```C
    #include <inttypes.h>

    #define NEOPIXEL_PIN    GPIO_NUM_8    /* builtin ws2812b led */
    #define PIXEL_COUNT     1

    tNeopixelContext neopixel = neopixel_Init(PIXEL_COUNT, NEOPIXEL_PIN);
    
    while (true)
    {
        tNeopixel pixel[] =
        {
            { 0, NP_RGB(16, 0, 0) }, /* red */
        };

        ESP_LOGI(TAG, "[%s] Starting", __func__);
        if (neopixel_SetPixel(neopixel, &pixel[0], 1))
        {
            ESP_LOGW(TAG, "SetPixel was TRUE, [ %"PRIu32" ] [ %"PRIu32" ]", pixel[0].index, pixel[0].rgb);
        }
        else
        {
            ESP_LOGW(TAG, "SetPixel was FALSE");
        }
        vTaskDelay(pdMS_TO_TICKS(1000));
        ESP_LOGI(TAG, "[%s] Finished", __func__);
    }
```

Am I missing something here?

Thanks in advance!

**Comment by jfdona23** [comment]
Last minute update:

I've tried once again the solution mentioned in #2, but this time cleaned the build folder first and it worked!

Now, I'm curious what changes from `I2S_STD_MSB_SLOT_DEFAULT_CONFIG` to `I2S_STD_PHILIPS_SLOT_DEFAULT_CONFIG`? At first glance, I see it only changes `.bit_shift` but not sure what this implies.
I would like to understand it a little bit better, so I can maybe propose a patch for it =)

Thanks again for this library!

**Comment by 0xjmux** [comment]
Same issue here - LED 0 stayed stuck on Green, and wouldn't turn off. Changing that constant fixed the issue. 

About my setup: I'm using an ESP32-S3 on a custom PCB, with a simple BSS138 mosfet logic-level converter between GPIO21 and my LED matrix. The issue was present using the example program in this repo. 

I think this issue has to do with the timing requirements of the WS2812B based on [the issues mentioned with Adafruit's library in the past](https://forums.adafruit.com/viewtopic.php?t=78039), but I'm not familiar enough with the spec to be much more help than that. 

Thanks for the library Zorxx, it's really nice!

**Comment by zorxx** [comment]
I've gotten an ESP32-C6 device with onboard WS2812B and reproduced the problem you see. Using the PHILIPS I2S slot configuration does indeed fix the issue and doesn't appear to have any negative impact on other WS2812B devices that I've been able to test.
